service: pacdivio-website

plugins:
  - serverless-offline
  # - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1

functions:
  hello:
    handler: dist/handler.hello
    events:
      - http:
          method: GET
          path: '{path+}'
